// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA4vrUCEApcih07lCUqPBlM3gXcx6bW58',
    appId: '1:803871607568:web:3d762dbd858dc75f5bb395',
    messagingSenderId: '803871607568',
    projectId: 'maloookcoffeeshop',
    authDomain: 'maloookcoffeeshop.firebaseapp.com',
    storageBucket: 'maloookcoffeeshop.appspot.com',
    measurementId: 'G-RQW542R9BC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADbWUTB1F8SXJQF9RL2MwAUonEc07k9Ds',
    appId: '1:803871607568:android:87c3705bf618ada35bb395',
    messagingSenderId: '803871607568',
    projectId: 'maloookcoffeeshop',
    storageBucket: 'maloookcoffeeshop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOc0whVlBXAgjXrUlgxeT1RHRnuQFqYH0',
    appId: '1:803871607568:ios:375a06dd63eca18f5bb395',
    messagingSenderId: '803871607568',
    projectId: 'maloookcoffeeshop',
    storageBucket: 'maloookcoffeeshop.appspot.com',
    iosBundleId: 'com.example.maloooookCoffeeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOc0whVlBXAgjXrUlgxeT1RHRnuQFqYH0',
    appId: '1:803871607568:ios:375a06dd63eca18f5bb395',
    messagingSenderId: '803871607568',
    projectId: 'maloookcoffeeshop',
    storageBucket: 'maloookcoffeeshop.appspot.com',
    iosBundleId: 'com.example.maloooookCoffeeShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA4vrUCEApcih07lCUqPBlM3gXcx6bW58',
    appId: '1:803871607568:web:199caec6889b962c5bb395',
    messagingSenderId: '803871607568',
    projectId: 'maloookcoffeeshop',
    authDomain: 'maloookcoffeeshop.firebaseapp.com',
    storageBucket: 'maloookcoffeeshop.appspot.com',
    measurementId: 'G-D0BFHFQWDC',
  );
}
